---

galaxy_info:
  author: Geert Roks
  description: Manages the installation of ROCm for AMD GPU applications development
  company: ETH Zürich - Systems Group

  license: MIT

  min_ansible_version: 2.15

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
